export default {
  FB_APP_ID_IOS: "FB_APP_ID_IOS",
  FB_APP_ID_ANDROID: "FB_APP_ID_ANDROID",
  FB_GET_EMAIL_URL: "FB_GET_EMAIL_URL",
  EXPO_CLIENT_ID: "",
  IOS_CLIENT_ID: "",
  ANDROID_CLIENT_ID: "",
  WEB_CLIENT_ID: "",
};
