export default {
  FB_APP_ID: "FB_APP_ID",
  FB_REDIRECT_URI: "FB_REDIRECT_URI",
  FB_GET_EMAIL_URL: "FB_GET_EMAIL_URL",
  EXPO_CLIENT_ID: "EXPO_CLIENT_ID",
  IOS_CLIENT_ID: "IOS_CLIENT_ID",
  ANDROID_CLIENT_ID: "ANDROID_CLIENT_ID",
  GG_GET_EMAIL_URL: "GG_GET_EMAIL_URL",
};
